name: Change detection

on:
  workflow_call:
    inputs:
      exclude-dependents:
        description: 'Lerna boostrap filter-option, exclude all transitive dependents when running a command with --since'
        default: false
        type: boolean
      as-enumeration:
        description: 'Get scope as "[plasma-temple]", etc'
        default: false
        type: boolean
      ref:
          type: string
          description: "Manual set repo ref"
          default: ''
    outputs:
      SCOPE:
        description: "scope collection"
        value: ${{ jobs.run.outputs.SCOPE }}
      HAS_SCOPE:
        description: "has scope"
        value: ${{ jobs.run.outputs.HAS_SCOPE }}
      HAS_DOCUMENTATION_CHANGED:
        description: ""
        value: ${{ jobs.run.outputs.HAS_DOCUMENTATION_CHANGED }}
      HAS_PLASMA_TEMPLE_DOCS:
        description: ""
        value: ${{ jobs.run.outputs.HAS_PLASMA_TEMPLE_DOCS }}
      HAS_PLASMA_TEMPLE:
        description: ""
        value: ${{ jobs.run.outputs.HAS_PLASMA_TEMPLE }}
      PACKAGES_ENUMERATION:
        description: ""
        value: ${{ jobs.run.outputs.PACKAGES_ENUMERATION }}
jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      SCOPE: ${{ steps.set-output.outputs.SCOPE }}
      HAS_SCOPE: ${{ steps.set-output.outputs.HAS_SCOPE }}
      HAS_DOCUMENTATION_CHANGED: ${{ steps.set-output.outputs.HAS_DOCUMENTATION_CHANGED }}
      HAS_PLASMA_TEMPLE_DOCS: ${{ steps.set-output.outputs.HAS_PLASMA_TEMPLE_DOCS }}
      HAS_PLASMA_TEMPLE: ${{ steps.set-output.outputs.HAS_PLASMA_TEMPLE }}
      PACKAGES_ENUMERATION: ${{ steps.set-output.outputs.PACKAGES_ENUMERATION }}

    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 0
          ref: ${{ inputs.ref }}

      - name: Prepare environment
        uses: ./.github/actions/prepare-environment

      - name: Set exclude-dependents env
        if: ${{ inputs.exclude-dependents }}
        run: echo "EXCLUDE_DEPENDENTS=--exclude-dependents" >> $GITHUB_ENV

      - name: Get lerna ls output
        shell: bash
        id: changed-state
        run: |
          #INFO: `jq -c` => Делаем вывод в одну JSON строку
          echo "CHANGED_STATE=$(npx lerna la --json --since=$(git merge-base --fork-point origin/dev) ${{ env.EXCLUDE_DEPENDENTS }} | jq -c)" >> "$GITHUB_OUTPUT"

      - name: Computed scope state
        id: scope
        uses: actions/github-script@v6
        env:
          CHANGED_STATE: ${{ toJSON(steps.changed-state.outputs.CHANGED_STATE) }}
          AS_ENUMERATION: ${{ inputs.as-enumeration }}
        with:
          script: |
            const processingScope = require('./.github/processing-scope.js');

            return processingScope();

      - name: Set "GITHUB_OUTPUT"
        id: set-output
        run: |
          echo "SCOPE=${{ fromJSON(steps.scope.outputs.result).SCOPE }}" >> $GITHUB_OUTPUT
          echo "HAS_SCOPE=${{ fromJSON(steps.scope.outputs.result).HAS_SCOPE }}" >> $GITHUB_OUTPUT
          echo "HAS_PLASMA_TEMPLE_DOCS=${{ fromJSON(steps.scope.outputs.result).HAS_PLASMA_TEMPLE_DOCS }}" >> $GITHUB_OUTPUT
          echo "HAS_DOCUMENTATION_CHANGED=${{ fromJSON(steps.scope.outputs.result).HAS_DOCUMENTATION_CHANGED }}" >> $GITHUB_OUTPUT
          echo "HAS_PLASMA_TEMPLE=${{ fromJSON(steps.scope.outputs.result).HAS_PLASMA_TEMPLE }}" >> $GITHUB_OUTPUT
          echo "PACKAGES_ENUMERATION=${{ fromJSON(steps.scope.outputs.result).PACKAGES_ENUMERATION }}" >> $GITHUB_OUTPUT

