name: Clean up S3

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  clean:
    name: Clean up S3
    runs-on: ubuntu-latest
    env:
      PR_NAME: pr-${{ github.event.number }}
    steps:
      - name: s3 Clean artifacts made for closed pr
        uses: vitorsgomes/s3-rm-action@master
        with:
          args: --recursive
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET_2 }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: ${{ secrets.AWS_ENDPOINT }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          PATH_TO_DELETE: "pr/${PR_NAME}"
