name: Cypress reusable workflow

on:
  workflow_call:
    inputs:
      with-react-17:
        type: boolean
        default: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      COVERAGE: true

    steps:
      - uses: actions/checkout@v4
        with:
           show-progress: false

      - name: Prepare environment
        uses: ./.github/actions/prepare-environment

      - name: Install React 17
        if:  ${{ inputs.with-react-17 }}
        run: |
          npm i --no-progress react@17 react-dom@17 @types/react@17.0.40 @types/react-dom@17 --prefix="./packages/plasma-temple"

      - name: Lerna bootstrap
        run: npx lerna bootstrap

      - name: Run Cypress CT for Plasma Temple
        if: ${{ success() }}
        run: npm run cy:temple:run-ct

      - name: Save artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@master
        with:
          name: Test Artifacts
          path: ${{ github.workspace }}/cypress
