name: Cypress component testing

on:
  pull_request:
    branches:
      - main

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  cypress-temple:
    uses: ./.github/workflows/cypress-common.yml
    secrets: inherit

  cypress-temple-react-17:
    uses: ./.github/workflows/cypress-common.yml
    with:
      with-react-17: true
    secrets: inherit

