name: Release Latest

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: Release Latest
    uses: ./.github/workflows/publish-common.yml
    with:
      with-update-package-lock: true
    secrets:
      gh_token: ${{ secrets.GH_TOKEN }}
      npm_registry_token: ${{ secrets.NPM_REGISTRY_TOKEN }}

