name: Typescript coverage

on:
  pull_request:
    branches:
      - main

concurrency:
  # New commit on branch cancels running workflows of the same branch
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  typescript-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Prepare environment
        uses: ./.github/actions/prepare-environment

      - name: Lerna bootstrap
        run: npx lerna bootstrap

      - name: Run Typescript Coverage
        if: ${{ always() }}
        run: npm run typescript-coverage

      - name: Save artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@master
        with:
          name: Typescript Coverage Report Artifacts
          path: ${{ github.workspace }}/packages/plasma-temple/coverage-ts/
